name: GoodAir ML Random Forest

on:
  schedule:
    - cron: '35 * * * *'
  workflow_dispatch:

jobs:
  ml-random-forest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn sqlalchemy psycopg2-binary

      - name: Run Random Forest
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: python predict_temp.py